# -*- coding: utf-8 -*-
"""basicpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYCZ5BeWt1zKAiG4c7CO4dnzPWwbX7sX
"""

#Home work

#1


a = 10
b = 20

if (a>b):
  print("b is smaller than a")
else:
  print ("a is smaller than b")


#2


a = 0
b = 1

if (a=b):
  print("True")
if (a<b):
  print("false")
if(a>b):
  print("a is true b is false")
else:
  print("not defined")


#3


def choice(b)
  match a:
    case 0:
      print(" tell about rain")
    case 1:
      print(" tell about sun")
    case 2:
      print("tell about nature")
    case 3:
      print("tell about the planetary system")
    case 4:
      print("tell about computer and its uses")
    case default:
      return "no such choice"
ch = choice(3)
 print(ch)



#Functions Homework


#1

def algebra(a,b):
  return a+b
  return a-b
  return a*b
  return a/b

al = algebra(999,456)
  print(al)


#2

def christmas(name):
  print(name +"here is your christmas gift")

na = christmas("Steve")


#3

def house(a):
  return a
  print(" check your House Number mentioned above")
ho = house(90)
 print(ho)









def algebra(a,b):
  return a+b
  return a-b
  return a*b
  return a/b

al = algebra(999,456)
print(al)





def choice(b):
  match a:
    case 0:
      print(" tell about rain")
    case 1:
      print(" tell about sun")
    case 2:
      print("tell about nature")
    case 3:
      print("tell about the planetary system")
    case 4:
      print("tell about computer and its uses")
    case default:
      return "no such choice"
ch = choice(0)
print(ch)

a = int(input("Enter the number"))

if ((a%2)==0):
  print("The number is even")
else:
  print("The number is odd")

a = int(input("Enter the number"))

if (a==0):
  print("The number is not positive or negative")
elif(a>0):
  print("The number is positive")
else:
  print("The number is negative")

str1 = "Hari"
str2 = " "
for i in str1:
  str2 = i+str2

print(str2)

list1 = [1,2,3]
list1.reverse()
print(list1)